# -*- coding: utf-8 -*-
"""AI Resume & Cover Letter Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZR2C9SYtI3o66dU9Jw74IZbBmtPfm4k

# - transformers: for using pre-trained language models like GPT-2, BERT, etc.
# - gradio: for creating user-friendly web interfaces for ML **models**
"""

!pip install transformers gradio

"""# Import the pipeline function and set_seed utility from the Hugging Face transformers library.
# Import the Gradio library to create an interactive web interface for the model.
"""

from transformers import pipeline, set_seed
import gradio as gr

"""# Create a text generation pipeline using the pre-trained GPT-2 model.
# Set a random seed to make the text generation results reproducible.


"""

generator = pipeline('text-generation', model='gpt2')
set_seed(42)

# Define a function to generate a resume summary and cover letter using user inputs.
def generate_resume(job_title, experience, skills, career_goals):

# Construct a prompt that asks the language model to generate a resume summary and cover letter
    prompt = f"""
    Write a professional resume summary and a cover letter for the following:
    Job Title: {job_title}
    Experience: {experience}
    Skills: {skills}
    Career Goals: {career_goals}

    Resume Summary:
    """

# Use the text-generation pipeline (GPT-2) to generate output based on the prompt.
# Limit the response length to 300 tokens and return only one generated sequence.
    output = generator(prompt, max_length=300, num_return_sequences=1)[0]['generated_text']

# Check if the model included a "Cover Letter:" section in the generated text
    if "Cover Letter:" in output:
# If yes, split the output into resume and cover letter parts
        resume_part = output.split("Cover Letter:")[0].strip()
        cover_letter_part = "Cover Letter:" + output.split("Cover Letter:")[1].strip()
    else:
# If not, return the entire output as resume and note that cover letter wasn't generated
        resume_part = output
        cover_letter_part = "Not generated"

# Return both parts as a tuple
    return resume_part, cover_letter_part

# Create a Gradio interface to interact with the generate_resume function.
iface = gr.Interface(
    fn=generate_resume,  # The function to call when the user submits input

# Define input components: four textboxes for job title, experience, skills, and career goals
    inputs=[
        gr.Textbox(label="Job Title"),
        gr.Textbox(label="Experience (in brief)"),
        gr.Textbox(label="Skills (comma-separated)"),
        gr.Textbox(label="Career Goals"),
    ],

# Define output components: two textboxes to display the resume summary and cover letter
    outputs=[
        gr.Textbox(label="Resume Summary"),
        gr.Textbox(label="Cover Letter"),
    ],
# Set the title and description shown at the top of the web app
    title="AI Resume & Cover Letter Generator",
    description="Enter your info to get an AI-generated resume summary and cover letter using GPT-2."
)

# Launch the Gradio web interface in a local browser window
iface.launch()