# -*- coding: utf-8 -*-
"""AI Resume & Cover Letter Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZR2C9SYtI3o66dU9Jw74IZbBmtPfm4k
"""

!pip install transformers gradio

from transformers import pipeline, set_seed
import gradio as gr

generator = pipeline('text-generation', model='gpt2')
set_seed(42)  # For reproducibility

def generate_resume(job_title, experience, skills, career_goals):
    prompt = f"""
    Write a professional resume summary and a cover letter for the following:
    Job Title: {job_title}
    Experience: {experience}
    Skills: {skills}
    Career Goals: {career_goals}

    Resume Summary:
    """
    output = generator(prompt, max_length=300, num_return_sequences=1)[0]['generated_text']

    # Split for resume and cover letter
    if "Cover Letter:" in output:
        resume_part = output.split("Cover Letter:")[0].strip()
        cover_letter_part = "Cover Letter:" + output.split("Cover Letter:")[1].strip()
    else:
        resume_part = output
        cover_letter_part = "Not generated"

    return resume_part, cover_letter_part

iface = gr.Interface(
    fn=generate_resume,
    inputs=[
        gr.Textbox(label="Job Title"),
        gr.Textbox(label="Experience (in brief)"),
        gr.Textbox(label="Skills (comma-separated)"),
        gr.Textbox(label="Career Goals"),
    ],
    outputs=[
        gr.Textbox(label="Resume Summary"),
        gr.Textbox(label="Cover Letter"),
    ],
    title="AI Resume & Cover Letter Generator",
    description="Enter your info to get an AI-generated resume summary and cover letter using GPT-2."
)

iface.launch()